config/routes.rb
Rails.application.routes.draw do

  get 'search', to: 'search#search'
  resources :articles

end

app/models/article.rb
require 'elasticsearch/model'

class Article < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  # includes

  # validation
  validates :title, presence: true
  validates :text, presence: true

  # elasticsearch queries
  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['title^10', 'text']
          }
        },
        highlight: {
          pre_tags: ['<em>'],
          post_tags: ['</em>'],
          fields: {
            title: {},
            text: {}
          }
        }
      }
    )
  end

  # elasticsearch mapping
  settings index: { number_of_shards: 1} do
    mappings dynamic: 'false' do
      indexes :title, analyzer: 'english', index_options: 'offsets'
      indexes :text, analyzer: 'english'
    end
  end
end
# Delete the previous articles index in Elasticsearch
Article.__elasticsearch__.client.indices.delete index: Article.index_name rescue nil

# Create the new index with the new mapping
Article.__elasticsearch__.client.indices.create \
  index: Article.index_name,
  body: { settings: Article.settings.to_hash, mappings: Article.mappings.to_hash }

# Index all article records from the DB to Elasticsearch
Article.import

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find params[:id]
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new article_params
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  private
  def article_params
    params.require(:article).permit :title, :text
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    if params[:q].nil?
      @articles = []
    else
      @articles = Article.search params[:q]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/articles/index.html.haml
%h1 Articles

%ul
  - @articles.each do |article|
    %li
      %h3= article.title
      %p= article.text

= link_to 'New Article', new_article_path

app/views/articles/new.html.haml
%h1 New Article
= form_for :article, url: articles_path do |f|
  - if @article.present? && @article.errors.any?
    #error_explanation
      %h2= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg
  %p
    =f.label :title
    %br
    =f.text_field :title
  %p
    =f.label :text
    %br
    =f.text_area :text

  %p
    =f.submit

= link_to '<- Back', articles_path

app/views/articles/show.html.haml
%h1= "Artile #{@article.title}"

%p
  %strong Title
  = @article.title

%p
  %strong Text
  = @article.text

= link_to '<- Back', articles_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Blog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/search/search.html.haml
%h1 Article Search
=form_for search_path, method: :get do |f|
  %p
    = f.label "Search for"
    = text_field_tag :q, params[:q]
    = submit_tag "Go", name: nil

%ul
  -@articles.each do |article|
    %li
      %h3
        = link_to article.try(:highlight).try(:title) ? article.highlight.title[0].html_safe : article.title,
            controller: "articles",
            action: "show",
            id: article._id
      -if article.try(:highlight).try(:text)
        -article.highlight.text.each do |snippet|
          %p= snippet.html_safe